bbmerci/bbmerci/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from products.views import ProductsListView

urlpatterns = [
    path('', ProductsListView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path("products/", include("products.urls")),
    path("users/", include("users.urls")),
    path("orders/", include("orders.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bbmerci/orders/urls.py
from django.urls import path
from .views import MyOrderView, AddToOrderView

urlpatterns = [
    path('my_order', MyOrderView.as_view(), name="my_order"),
    path('add_to_order', AddToOrderView.as_view(), name="add_to_order"),
]

bbmerci/products/urls.py
from django.urls import path
from .views import ProductsFormView, ProductsListView, ProductListApiView

urlpatterns = [
    path('', ProductsListView.as_view(), name="list_product"),
    path('api_list', ProductListApiView.as_view(), name="list_product_api"),
    path('add', ProductsFormView.as_view(), name="add_product"),
]

bbmerci/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import RegisterView, ProfileView

urlpatterns = [
    path('login', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
    path("register", RegisterView.as_view(), name="register"),
    path("profile", ProfileView.as_view(), name="profile"),
]

bbmerci/orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product

class OrderModel(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    is_active=models.BooleanField(verbose_name="Activa", default=True)
    creation_date=models.DateTimeField(verbose_name="Creacion", auto_now_add=True)
    update_date=models.DateTimeField(verbose_name="Ultima Actualizacion", auto_now=True)

    def __str__(self) -> str:
        return f"order {self.id} by {self.user.username}"
    
class OrderProductModel(models.Model):
    order=models.ForeignKey(OrderModel, on_delete=models.CASCADE)
    product=models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity=models.IntegerField(verbose_name="Cantidad", default=1)
    
    def __str__(self) -> str:
        return f"{self.quantity} of {self.product} from order {self.order}"
    

bbmerci/products/models.py
from django.db import models


class Product(models.Model):
    product = models.TextField(
        verbose_name="Product",
        max_length=50,
    )
    description = models.TextField(
        verbose_name="Descripción del Producto",
        max_length=300,
    )
    price = models.FloatField(
        verbose_name="Precio",
    )
    available = models.BooleanField(
        verbose_name="Disponible",
        default=True,
    )
    image = models.ImageField(
        verbose_name="Foto",
        upload_to="imgs",
        null=True,
        blank=True,
    )

    def __str__(self) -> str:
        return self.product
    

bbmerci/users/models.py
from django.db import models

# Create your models here.

bbmerci/orders/forms.py
from django.forms import ModelForm
from .models import OrderProductModel

class AddProductForm(ModelForm):
    class Meta:
        model = OrderProductModel
        fields = ["product"]

bbmerci/products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.Form):
    product = forms.CharField(
        label="Nombre del Producto",
        max_length=50,
    )
    description = forms.CharField(
        label="Descripción del Producto",
        max_length=300,
    )
    price = forms.FloatField(
        label="Precio",
        min_value=100.0,
    )
    available = forms.BooleanField(
        label="Disponible",
        required=False,
        initial=True,
    )
    image = forms.ImageField(
        label="Foto",
        required=False,
    )

    def save(self):
        print("saving")
        Product.objects.create(
            product = self.cleaned_data["product"],
            description = self.cleaned_data["description"],
            price = self.cleaned_data["price"],
            available = self.cleaned_data["available"],
            image  = self.cleaned_data["image"],
        )

bbmerci/orders/views.py
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.views.generic import DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import OrderModel, OrderProductModel
from .forms import AddProductForm

class MyOrderView(LoginRequiredMixin, DetailView):
    model = OrderModel
    template_name = "my_order.html"
    context_object_name = "my_order"

    def get_object(self, queryset=None):
        return OrderModel.objects.filter(is_active=True, user=self.request.user).first()
    
class AddToOrderView(LoginRequiredMixin, CreateView):
    template_name = "add_to_order.html"
    form_class = AddProductForm
    success_url = reverse_lazy("my_order")

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        order, _ = OrderModel.objects.get_or_create(is_active=True, user=self.request.user)
        form.instance.order = order
        form.instance.quantity = 1
        form.save()
        return super().form_valid(form)

bbmerci/products/views.py
from django.views import generic
from django.urls import reverse_lazy

from rest_framework.views import APIView
from rest_framework.response import Response

from .forms import ProductForm
from .models import Product
from .serializers import ProductSerializer


class ProductsFormView(generic.FormView):
    template_name= "add_product.html"
    form_class = ProductForm
    success_url= reverse_lazy("list_product")

    def form_valid(self, form):
        print("validando")
        form.save()
        return super().form_valid(form)
    
class ProductsListView(generic.ListView):
    model=Product
    template_name="list_product.html"
    context_object_name="products"

class ProductListApiView(APIView):
    authentication_classes = [] #[SessionAuthentication, BasicAuthentication]
    permission_classes = [] #[IsAuthenticated]

    def get(self, request):
        products=Product.objects.all()
        serializer=ProductSerializer(products, many=True)
        return Response(serializer.data)

bbmerci/users/views.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.views import generic
from django.urls import reverse_lazy

class RegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = "register.html"
    success_url = reverse_lazy("login")

class ProfileView(generic.CreateView):
    form_class = UserChangeForm
    template_name = "profile.html"
    success_url = reverse_lazy("list_product")

bbmerci/orders/templates/add_to_order.html
{% extends "base.html" %}

{% block content %}
<h1 class="text-3xl font-bold underline">Agregar Producto</h1>


<form action="{% url "add_product" %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Agregar</button>
</fom>
{% endblock content %}

bbmerci/orders/templates/my_order.html
{% extends "base.html" %}
{% load mathfilters %}

{% block content %}
<h1 class="text-3xl font-bold underline">Mi Orden</h1>

<button>Agregar</button>
<ul class="grid grid-cols-1 gap-4 lg:grid-cols-4 lg:gap-8">
    {% for product in my_order.orderproductmodel_set.all %}
    <il>
        <a href="#" class="group relative block overflow-hidden">
        <button
          class="absolute end-4 top-4 z-10 rounded-full bg-white p-1.5 text-gray-900 transition hover:text-gray-900/75"
        >
      
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="size-4"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
            />
          </svg>
        </button>
        {% if product.product.image %}
        <img
          src="{{product.product.image.url}}"
          alt="{{product.product.product}}"
          class="h-64 w-64l object-cover transition duration-500 group-hover:scale-105 sm:h-72"
        />
        {% endif %}
        <div class="relative border border-gray-100 bg-white p-6">
          <h3 class="mt-4 text-lg font-medium text-gray-900">{{product.product.product}}</h3>
      
          <p class="mt-1.5 text-sm text-gray-700">${{product.product.price |mul:product.quantity}}</p>
          <p class="mt-1.5 text-sm text-gray-700">cantidad: {{product.quantity}}</p>
        </div>
      </a>            
    </il>
    {%empty%}
    <p class="mt-1.5 text-sm text-gray-700">No hay productos en esta orden</p>
    {% endfor %}
</ul>
{% endblock content %}

bbmerci/products/templates/add_product.html
{% extends "base.html" %}

{% block content %}
<h1 class="text-3xl font-bold underline">Agregar Producto</h1>


<form action="{% url "add_product" %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Agregar</button>
</fom>
{% endblock content %}

bbmerci/products/templates/list_product.html
{% extends "base.html" %}

{% block content %}
<h1 class="text-3xl font-bold underline">Nuestros Productos</h1>

<button>Agregar</button>
<ul class="grid grid-cols-1 gap-4 lg:grid-cols-4 lg:gap-8">
    {% for product in products %}
    <il>
        <a href="#" class="group relative block overflow-hidden">
        <button
          class="absolute end-4 top-4 z-10 rounded-full bg-white p-1.5 text-gray-900 transition hover:text-gray-900/75"
        >
          <span class="sr-only">Wishlist</span>
      
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="size-4"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
            />
          </svg>
        </button>
        {% if product.image %}
        <img
          src="{{product.image.url}}"
          alt="{{product.product}}"
          class="h-64 w-64l object-cover transition duration-500 group-hover:scale-105 sm:h-72"
        />
        {% endif %}
        <div class="relative border border-gray-100 bg-white p-6">
          <span class="whitespace-nowrap bg-yellow-400 px-3 py-1.5 text-xs font-medium"> New </span>
      
          <h3 class="mt-4 text-lg font-medium text-gray-900">{{product.product}}</h3>
      
          <p class="mt-1.5 text-sm text-gray-700">${{product.price}}</p>
            
          <form 
          action = {% url "add_to_order" %}
          class="mt-4" 
          method = "post">
            {% csrf_token %}
            <input type="hidden" name="product" value ="{{product.id}}" >
            <button
              class="block w-full rounded bg-yellow-400 p-4 text-sm font-medium transition hover:scale-105"
            >
              Agregar a Pedido
            </button>
          </form>
          
        </div>
      </a>            
    </il>
    {% endfor %}
</ul>
{% endblock content %}

bbmerci/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Backery by Merci</title>
</head>
<body>
    <header class="bg-white">
        <div class="mx-auto flex h-16 max-w-screen-xl items-center gap-8 px-4 sm:px-6 lg:px-8">
          <a class="block text-teal-600" href="#">
            <span class="sr-only">Home</span>
            <img src="/imgs/logo.jpg" alt="logo" class="mx-auto flex h-16 max-w-screen-xl items-center gap-8 px-4 sm:px-6 lg:px-8">
          </a>
      
          <div class="flex flex-1 items-center justify-end md:justify-between">
            <nav aria-label="Global" class="hidden md:block">
              {% comment %} <ul class="flex items-center gap-6 text-sm">
                <li>
                  <a class="text-gray-500 transition hover:text-gray-500/75" href="#"> About </a>
                </li>
      
                <li>
                  <a class="text-gray-500 transition hover:text-gray-500/75" href="#"> Careers </a>
                </li>
      
                <li>
                  <a class="text-gray-500 transition hover:text-gray-500/75" href="#"> History </a>
                </li>
      
                <li>
                  <a class="text-gray-500 transition hover:text-gray-500/75" href="#"> Services </a>
                </li>
      
                <li>
                  <a class="text-gray-500 transition hover:text-gray-500/75" href="#"> Projects </a>
                </li>
      
                <li>
                  <a class="text-gray-500 transition hover:text-gray-500/75" href="#"> Blog </a>
                </li>
              </ul> {% endcomment %}
            </nav>
      
            <div class="flex items-center gap-4">
              <div class="sm:flex sm:gap-4">
                {% if user.is_authenticated %}
                    {{user.first_name}}
                    <a
                      class="hidden rounded-md bg-gray-100 px-5 py-2.5 text-sm font-medium text-teal-600 transition hover:text-teal-600/75 sm:block"
                      href="{% url "profile" %}"
                    >
                    Perfil
                    </a>
                    <a
                      class="hidden rounded-md bg-gray-100 px-5 py-2.5 text-sm font-medium text-teal-600 transition hover:text-teal-600/75 sm:block"
                      href="{% url "my_order" %}"
                    >
                    Mi Pedido
                    </a>
                    <form action="{% url "logout" %}" method="post">
                        {% csrf_token %}
                        <button
                        class="block rounded-md bg-teal-600 px-5 py-2.5 text-sm font-medium text-white transition hover:bg-teal-700"
                        type="submit"
                        >
                        Logout
                        </button>
                    </form>
                    
                {% else %}
                    <a
                    class="block rounded-md bg-teal-600 px-5 py-2.5 text-sm font-medium text-white transition hover:bg-teal-700"
                    href="{% url "login" %}"
                    >
                    Login
                    </a>
        
                    <a
                    class="hidden rounded-md bg-gray-100 px-5 py-2.5 text-sm font-medium text-teal-600 transition hover:text-teal-600/75 sm:block"
                    href="{% url "register" %}"
                    >
                    Registro
                    </a>
                {% endif %}
              </div>
      
              <button
                class="block rounded bg-gray-100 p-2.5 text-gray-600 transition hover:text-gray-600/75 md:hidden"
              >
                <span class="sr-only">Toggle menu</span>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  class="size-5"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  stroke-width="2"
                >
                  <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </header>

    <div class="container mx-auto px-4">
        {% block content %}{% endblock content %}
    </div>
</body>
</html>